---
title: "01_CleanData"
author: "Bryan"
date: "`r Sys.Date()`"
output: html_document
---

## Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(openxlsx)
```

## Load data
```{r}
demo_data = read.csv('/Users/bryanchen/Desktop/Med School/Pre-Clerkships/Research/ABCD/abcd-data-release-5.1/core/abcd-general/abcd_p_demo.csv')
age_data = read.csv('/Users/bryanchen/Desktop/Med School/Pre-Clerkships/Research/ABCD/abcd-data-release-5.1/core/abcd-general/abcd_y_lt.csv') %>% 
  select(src_subject_id, eventname, interview_age)
upps_data = read.csv('/Users/bryanchen/Desktop/Med School/Pre-Clerkships/Research/ABCD/abcd-data-release-5.1/core/mental-health/mh_y_upps.csv') %>%
  left_join(age_data, by = join_by(src_subject_id, eventname)) %>%
  group_by(src_subject_id) %>%
  filter(n() == 3) %>% # Only keep those with all three timepoints
  ungroup()
sleep_data = read.csv('/Users/bryanchen/Desktop/Med School/Pre-Clerkships/Research/ABCD/abcd-data-release-5.1/core/physical-health/ph_p_sds.csv')
```

## Clean
```{r}
# https://nda.nih.gov/data-structure/pdem02
# https://nda.nih.gov/data-structure/abcd_sds01
# https://nda.nih.gov/data-structure/abcd_mhy02
# https://nda.nih.gov/data-structure/abcd_upps01
upps_data_clean <- upps_data %>% rename(
    negative_urgency = upps_y_ss_negative_urgency,
    lack_of_perseverance = upps_y_ss_lack_of_perseverance,
    lack_of_planning = upps_y_ss_lack_of_planning,
    sensation_seeking = upps_y_ss_sensation_seeking,
    positive_urgency = upps_y_ss_positive_urgency
)
  
  
sleep_data_clean <- sleep_data %>% rename(
    duration = sleepdisturb1_p,
    delay_i = sleepdisturb2_p,
    reluctance_i = sleepdisturb3_p,
    difficulty_i = sleepdisturb4_p,
    fear_i = sleepdisturb5_p,
    jerk_i = sleepdisturb6_p,
    repetitive_i = sleepdisturb7_p,
    dream_i = sleepdisturb8_p,
    sweat_i = sleepdisturb9_p,
    wake_m = sleepdisturb10_p,
    back_asleep_i = sleepdisturb11_p,
    jerk_m = sleepdisturb12_p,
    breath_difficulty_m = sleepdisturb13_p,
    breath_unable_m = sleepdisturb14_p,
    snore_m = sleepdisturb15_p,
    sweat_m = sleepdisturb16_p,
    sleepwalking_m = sleepdisturb17_p,
    sleeptalking_m = sleepdisturb18_p,
    teethgrind_m = sleepdisturb19_p,
    scream_m = sleepdisturb20_p,
    nightmares_m = sleepdisturb21_p,
    morningwake = sleepdisturb22_p,
    morningtired = sleepdisturb23_p,
    morningparalysis = sleepdisturb24_p,
    daytimesleepiness = sleepdisturb25_p,
    narcolepsy = sleepdisturb26_p
)

clean_data <- function(df, timepoint) {
  upps_questions <- c('negative_urgency', 'lack_of_planning', 'sensation_seeking', 'positive_urgency', 'lack_of_perseverance', 'duration', 'delay_i', 'reluctance_i', 'difficulty_i', 'fear_i', 'jerk_i', 'repetitive_i', 'dream_i', 'sweat_i', 'wake_m', 'back_asleep_i', 'jerk_m', 'breath_difficulty_m', 'breath_unable_m', 'snore_m', 'sweat_m', 'sleepwalking_m', 'sleeptalking_m', 'teethgrind_m', 'scream_m', 'nightmares_m', 'morningwake', 'morningtired', 'morningparalysis', 'daytimesleepiness', 'narcolepsy')
  
  df %>%
    filter(eventname == timepoint) %>%
    left_join(sleep_data_clean, by = join_by(src_subject_id, eventname)) %>% #inclusion of eventname filters baseline data for both
    select(src_subject_id, any_of(upps_questions)) %>%
    drop_na(any_of(c('interview_age', 'sex', 'race_ethnicity', 'demo_prnt_marital_v2', 'demo_prnt_ed_v2', 'demo_prnt_empl_v2', 'demo_prnt_income_v2'))) %>%
    drop_na(any_of(upps_questions))
}

baseline_data <- clean_data(upps_data_clean, 'baseline_year_1_arm_1')
year2_FU <- clean_data(upps_data_clean, '2_year_follow_up_y_arm_1')
year4_FU <- clean_data(upps_data_clean, '4_year_follow_up_y_arm_1')

common_ids <- Reduce(intersect, list(baseline_data$src_subject_id, year2_FU$src_subject_id, year4_FU$src_subject_id))

baseline_data <- baseline_data[baseline_data$src_subject_id %in% common_ids, ] #%>%
  #select(!src_subject_id)
year2_FU <- year2_FU[year2_FU$src_subject_id %in% common_ids, ] #%>%
  #select(!src_subject_id)
year4_FU <- year4_FU[year4_FU$src_subject_id %in% common_ids, ] #%>%
  #select(!src_subject_id)

save(baseline_data, year2_FU, year4_FU, file = '/Users/bryanchen/Desktop/Med School/Pre-Clerkships/Research/ABCD/processedData.RData')

###
baseline_data_summed <- upps_data_clean %>%
    filter(eventname == 'baseline_year_1_arm_1') %>%
    left_join(sleep_data_clean, by = join_by(src_subject_id, eventname)) %>% #inclusion of eventname filters baseline data for both
    rowwise() %>%
    mutate(sleep_initiation_sum = sum(c_across(ends_with('_i')))) %>% #sums across selected measures
    mutate(sleep_maintenance_sum = sum(c_across(ends_with('_m')))) %>%
    select(negative_urgency, lack_of_planning, sensation_seeking, positive_urgency, lack_of_perseverance, duration, ends_with('_sum'))
```