---
title: "Chelsea Models"
author: "Bryan Chen"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: 
---


```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE, messAge=FALSE, warning=FALSE)

library(tidyverse)
library(openxlsx)
library(ggplot2)
library(bootnet)
library(qgraph)
library(lavaan)
library(mgm)
library(glmnet)
```

```{r}
load('/Users/bryanchen/Desktop/Med School/Pre-Clerkships/Research/ABCD/processedData.RData')
```

## Descriptives
```{r, results='asis'}
# summary(tableby(isAD~Age + Gender + Education + das_executive_v2+das_emotional_v2+das_behavior_cognitive_v2 + das_total_v2 + gds_total +
#                  updrs_Total + FAStotal + `DX:`, alldata))


```

## Testing Confirmatory Factor Analysis
```{r}
library(psych)
library(lavaan)
sleep_baseline_data <- baseline_data[, 7:ncol(baseline_data)]

fa.parallel(sleep_baseline_data, fm = "minres", fa = "fa")
efa_result <- fa(sleep_baseline_data, nfactors = 8, rotate = "oblimin", fm = "minres")
print(efa_result$loadings, cutoff = 0.3)
diagram(efa_result, sort = TRUE, cut = 0.3, cex = 0.5)

efa_result <- fa(sleep_baseline_data, nfactors = 7, rotate = "oblimin", fm = "minres")
print(efa_result$loadings, cutoff = 0.3)

efa_result <- fa(sleep_baseline_data, nfactors = 6, rotate = "oblimin", fm = "minres")
print(efa_result$loadings, cutoff = 0.3)

# efa_result <- fa(sleep_baseline_data, nfactors = 5, rotate = "oblimin", fm = "minres")
# print(efa_result$loadings, cutoff = 0.3)

# efa_result <- efa(sleep_baseline_data, nfactors = 1:8, rotation = 'oblimin')
# summary(efa_result)

# 7-factor model (split DIMS into DIS and DMS)
model_7f <- '
  DIS =~ delay_DIMS + reluctance_DIMS + difficulty_DIMS + fear_DIMS
  DMS =~ wake_DIMS + back_asleep_DIMS
  SBD =~ breath_difficulty + breath_unable + snore
  DOA =~ sleepwalking + scream + nightmares
  SWTD =~ jerk_i + repetitive + dream + jerk_m + sleeptalking + teethgrind
  DOES =~ morningwake + morningtired + morningparalysis + daytimesleepiness + narcolepsy
  SH =~ sweat_i + sweat_m
'

# 6-factor model (original Bruni)
model_6f <- '
  DIMS =~ delay_DIMS + reluctance_DIMS + difficulty_DIMS + fear_DIMS + wake_DIMS + back_asleep_DIMS
  SBD =~ breath_difficulty + breath_unable + snore
  DOA =~ sleepwalking + scream + nightmares
  SWTD =~ jerk_i + repetitive + dream + jerk_m + sleeptalking + teethgrind
  DOES =~ morningwake + morningtired + morningparalysis + daytimesleepiness + narcolepsy
  SH =~ sweat_i + sweat_m
'

# List of ordered variables (assuming all are ordinal)
ordered_items <- c('delay_DIMS', 'reluctance_DIMS', 'difficulty_DIMS', 'fear_DIMS',
                   'wake_DIMS', 'back_asleep_DIMS', 'breath_difficulty', 'breath_unable',
                   'snore', 'sleepwalking', 'sleeptalking', 'scream', 'jerk_i',
                   'repetitive', 'dream', 'sweat_i', 'sweat_m', 'teethgrind', 'morningwake', 'morningtired',
                   'morningparalysis', 'daytimesleepiness', 'narcolepsy')

# Fit both models
fit_7f <- cfa(model_7f, data = sleep_baseline_data, ordered = ordered_items, estimator = "WLSMV")
fit_6f <- cfa(model_6f, data = sleep_baseline_data, ordered = ordered_items, estimator = "WLSMV")

# Summarize fit
summary(fit_7f, fit.measures = TRUE, standardized = TRUE)
summary(fit_6f, fit.measures = TRUE, standardized = TRUE)

fitMeasures(fit_7f, c("cfi.scaled", "tli.scaled", "rmsea.scaled", "srmr"))
fitMeasures(fit_6f, c("cfi.scaled", "tli.scaled", "rmsea.scaled", "srmr"))

# Compare fit (only valid for nested models)
lavTestLRT(fit_7f, fit_6f)
```

## Longitudinal Network
```{r}
DIS <- c('delay_DIMS', 'reluctance_DIMS', 'difficulty_DIMS', 'fear_DIMS')
DMS <- c('wake_DIMS', 'back_asleep_DIMS')
  
baseline_data_summed <- baseline_data %>%
  rowwise() %>%
  mutate(DIS = sum(c_across(all_of(DIS)))) %>%
  mutate(DMS = sum(c_across(all_of(DMS)))) %>%
  select(negative_urgency, lack_of_planning, sensation_seeking, positive_urgency, lack_of_perseverance, duration, DIS, DMS)

year2_FU_summed <- year2_FU %>%
  rowwise() %>%
  mutate(DIS = sum(c_across(all_of(DIS)))) %>%
  mutate(DMS = sum(c_across(all_of(DMS)))) %>%
  select(negative_urgency, lack_of_planning, sensation_seeking, positive_urgency, lack_of_perseverance, duration, DIS, DMS)

year4_FU_summed <- year4_FU %>%
  rowwise() %>%
  mutate(DIS = sum(c_across(all_of(DIS)))) %>%
  mutate(DMS = sum(c_across(all_of(DMS)))) %>%
  select(negative_urgency, lack_of_planning, sensation_seeking, positive_urgency, lack_of_perseverance, duration, DIS, DMS)

type = rep('g', 8) # Treating as quasi-continuous
level = rep(1, 8)

baseline_matrix = data.matrix(baseline_data_summed) %>% scale()
baseline_network = mgm(data = baseline_matrix,
                       type = type,
                       level = level,
                       k = 2,
                       lambdaSel = 'EBIC',
                       lambdaGam = 0.5,
                       ruleReg = 'AND',
                       pbar = FALSE)

year2_matrix = data.matrix(year2_FU_summed) %>% scale()
year2_network = mgm(data = year2_matrix,
                    type = type,
                    level = level,
                    k = 2,
                    lambdaSel = 'EBIC',
                    lambdaGam = 0.5,
                    ruleReg = 'AND',
                    pbar = FALSE)

year4_matrix = data.matrix(year4_FU_summed) %>% scale()
year4_network = mgm(data = year4_matrix,
                    type = type,
                    level = level,
                    k = 2,
                    lambdaSel = 'EBIC',
                    lambdaGam = 0.5,
                    ruleReg = 'AND',
                    pbar = FALSE)

baseline_predict = predict(object = baseline_network,
                           data = baseline_matrix,
                           errorCon = 'R2',
                           errorCat = 'CC')$error

year2_predict = predict(object = year2_network,
                           data = year2_matrix,
                           errorCon = 'R2',
                           errorCat = 'CC')$error

year4_predict = predict(object = year4_network,
                           data = year4_matrix,
                           errorCon = 'R2',
                           errorCat = 'CC')$error

baseline_predict$R2_CC = ifelse(!is.na(baseline_predict$R2), baseline_predict$R2, baseline_predict$CC)
year2_predict$R2_CC = ifelse(!is.na(year2_predict$R2), year2_predict$R2, year2_predict$CC)
year4_predict$R2_CC = ifelse(!is.na(year4_predict$R2), year4_predict$R2, year4_predict$CC)

groups = append(rep('UPPS', 5), rep('SDSC', 3)) %>% factor
p_baseline = qgraph(baseline_network$pairwise$wadj,
             vsize = 8,
             layout = "spring",
              pie = baseline_predict$R2_CC,
             edge.width = 1.5,
             edge.color = baseline_network$pairwise$edgecolor, 
             labels = colnames(baseline_data_summed),
             palette = "pastel",
             GLratio = 2,
             legend.cex = .35,
             edge.labels = TRUE,
             groups = groups)

p_year2 = qgraph(year2_network$pairwise$wadj,
             vsize = 8,
             layout = "spring",
              pie = year2_predict$R2_CC,
             edge.width = 1.5,
             edge.color = year2_network$pairwise$edgecolor, 
             labels = colnames(year2_matrix),
             palette = "pastel",
             GLratio = 2,
             legend.cex = .35,
             edge.labels = TRUE,
             groups = groups)

p_year4 = qgraph(year4_network$pairwise$wadj,
             vsize = 8,
             layout = "spring",
              pie = year4_predict$R2_CC,
             edge.width = 1.5,
             edge.color = year4_network$pairwise$edgecolor, 
             labels = colnames(year4_matrix),
             palette = "pastel",
             GLratio = 2,
             legend.cex = .35,
             edge.labels = TRUE,
             groups = groups)

## Cross-lagged

### T1 -> T2
k = 8
adjMat = matrix(0, k, k)
rsquare = rep(0, k)

baseline_matrix_summed <- data.matrix(baseline_data_summed)
year2_matrix_summed <- data.matrix(year2_FU_summed)
colnames(baseline_matrix_summed) <- paste0(colnames(baseline_matrix_summed), '.1')
colnames(year2_matrix_summed) <- paste0(colnames(year2_matrix_summed), '.2')
baseline_year2_combined_matrix <- cbind(baseline_matrix_summed, year2_matrix_summed)

for (i in 1:k) {
  set.seed(222)
  lassoreg = cv.glmnet(as.matrix(baseline_year2_combined_matrix[,1:k]), as.matrix(baseline_year2_combined_matrix[,(k+1)]),
                                 family = 'gaussian',
                                 alpha = 1,
                                 standardize = TRUE)
  lambda = lassoreg$lambda.min
  rsquare[i] = lassoreg$glmnet.fit$dev.ratio[which(lassoreg$lambda == lambda)]
  adjMat[1:k, i] = coef(lassoreg, s = lambda, exact = FALSE)[2: (k+1)]
}

# Plot
groups = append(rep('UPPS', 5), rep('SDSC', 3)) %>% factor
labels = c('negative_urgency', 'lack_of_planning', 'sensation_seeking', 'positive_urgency', 'lack_of_perseverance', 'duration', 'DIS', 'DMS')
node_names = c('Negative Urgency', 'lack_of_planning', 'sensation_seeking', 'positive_urgency', 'lack_of_perseverance', 'duration', 'DIS', 'DMS')

# diag(adjMat) = 0

test_fig = qgraph(adjMat, 
                vsize = 8,
                layout = 'circular',
                edge.width = 1.5,
                pie = rsquare,
                fade = TRUE,
                labels = labels,
                groups = groups,
                legend = TRUE,
                # nodeNames = node_names,
                palette = "pastel",
                GLratio = 2.5,
                edge.labels = TRUE)

centrality(test_fig)
centralityPlot(test_fig, include = 'all', orderBy = 'OutExpectedInfluence')

### T2 -> T3
k = 8
adjMat = matrix(0, k, k)
rsquare = rep(0, k)

year2_matrix_summed <- data.matrix(year2_FU_summed)
year4_matrix_summed <- data.matrix(year4_FU_summed)
colnames(year2_matrix_summed) <- paste0(colnames(year2_matrix_summed), '.2')
colnames(year4_matrix_summed) <- paste0(colnames(year4_matrix_summed), '.3')
year2_year4_combined_matrix <- cbind(year2_matrix_summed, year4_matrix_summed)

for (i in 1:k) {
  set.seed(222)
  lassoreg = cv.glmnet(as.matrix(year2_year4_combined_matrix[,1:k]), as.matrix(year2_year4_combined_matrix[,(k+1)]),
                                 family = 'gaussian',
                                 alpha = 1,
                                 standardize = TRUE)
  lambda = lassoreg$lambda.min
  rsquare[i] = lassoreg$glmnet.fit$dev.ratio[which(lassoreg$lambda == lambda)]
  adjMat[1:k, i] = coef(lassoreg, s = lambda, exact = FALSE)[2: (k+1)]
}

# Plot
groups = append(rep('UPPS', 5), rep('SDSC', 3)) %>% factor
labels = c('negative_urgency', 'lack_of_planning', 'sensation_seeking', 'positive_urgency', 'lack_of_perseverance', 'duration', 'DIS', 'DMS')
node_names = c('Negative Urgency', 'lack_of_planning', 'sensation_seeking', 'positive_urgency', 'lack_of_perseverance', 'duration', 'DIS', 'DMS')

# diag(adjMat) = 0

test_fig = qgraph(adjMat, 
                vsize = 8,
                layout = 'circular',
                edge.width = 1.5,
                pie = rsquare,
                fade = TRUE,
                labels = labels,
                groups = groups,
                legend = TRUE,
                # nodeNames = node_names,
                palette = "pastel",
                GLratio = 2.5,
                edge.labels = TRUE)

centrality(test_fig)
centralityPlot(test_fig, include = 'all', orderBy = 'OutExpectedInfluence')
```


``` {r} 
getAdjMatList <- function(designMat, data){
  AdjMatList <- NULL
  lambdaList <- NULL
  k <- nrow(designMat)
  
  for (t in 1:(ncol(designMat) -1)){
    
    predictors <- as.matrix(data[, designMat[, t]])
    
    adjMat <- matrix(0, k, k)
    colnames(adjMat) <- designMat[, (t+1)]
    rownames(adjMat) <- colnames(predictors)
    
    lambdaVec <- rep(0,k)
      
    for (i in 1:k){
      
      set.seed(100)
      lassoreg <- cv.glmnet(x = predictors, 
                            y = data[, designMat[i , t+1 ]], 
                            family = "gaussian", alpha = 1, standardize=TRUE)
      
      lambdaVec[i] <- lassoreg$lambda.min
      
      adjMat[1:k,i] <- coef(lassoreg, s = lambdaVec[i], exact = FALSE)[2:(k+1)]
    }
    
    AdjMatList[[t]] <- adjMat
    lambdaList[[t]] <- lambdaVec
  }
  return(list(B = AdjMatList, lambdas = lambdaList))
}

getLavaanSyntax <- function(designMat, model = NULL){
  
  k <- nrow(designMat)
  
  regressions <- ""
  resVariances <- ""
  
  for (t in 1:(ncol(designMat) -1)){
    
    
    for (i in 1:k){
      
      predictors <- designMat[, t]
      
      if(!is.null(model)){
        
        predictors <- predictors[which(model[[t]][,i] != 0 )]
        
      }
      
      #regress variable on variables at the previous time point
      regressions <- paste(regressions, paste(designMat[i,(t+1)], "~", sep = ""), 
                           paste(predictors, collapse = "+"), "\n")
      
      resVariances <- paste(resVariances, paste(designMat[i,(t+1)], "~~", paste(designMat[(i : k), (t+1)], collapse = "+"), sep = ""), "\n")
    }
  }
  
  
  return(c(regressions, resVariances))
}

CreateSigB <- function(B, nonSigParam){
  
  sigB <- B
  
  if(nrow(nonSigParam) == 0){
    return(B)
  }else{
    for(i in 1: nrow(nonSigParam)){
      sigB[nonSigParam$rhs[i], nonSigParam$lhs[i]] <- 0
      
    }
    
    return(sigB)
  }
}

CreateSeparateB <- function(B, designMat){
  
  BList <- NULL
  
  for (t in 1:(ncol(designMat) -1)){
    
    k <- nrow(designMat)
    
    outcomes <- designMat[, (t + 1)]
    
    predictors <- designMat[, t]
    
    BList[[t]] <- B[predictors, outcomes]
    
  }
  
  return(BList)
}

baseline_matrix_summed <- data.matrix(baseline_data_summed)
year2_matrix_summed <- data.matrix(year2_FU_summed)
year4_matrix_summed <- data.matrix(year4_FU_summed)
colnames(baseline_matrix_summed) <- paste0(colnames(baseline_matrix_summed), '.1')
colnames(year2_matrix_summed) <- paste0(colnames(year2_matrix_summed), '.2')
colnames(year4_matrix_summed) <- paste0(colnames(year4_matrix_summed), '.3')
baseline_year2_combined_matrix <- cbind(baseline_matrix_summed, year2_matrix_summed)
full_matrix <- cbind(baseline_year2_combined_matrix, year4_matrix_summed)

designMat <- matrix(colnames(full_matrix), nrow = 8, ncol = 3, byrow = FALSE)


glmModel <- getAdjMatList(designMat = designMat , data = full_matrix)

groups = append(rep('UPPS', 5), rep('SDSC', 3)) %>% factor
labels = c('negative_urgency', 'lack_of_planning', 'sensation_seeking', 'positive_urgency', 'lack_of_perseverance', 'duration', 'DIS', 'DMS')
node_names = c('Negative Urgency', 'lack_of_planning', 'sensation_seeking', 'positive_urgency', 'lack_of_perseverance', 'duration', 'DIS', 'DMS')

adjMat <- glmModel[['B']][[1]]
diag(adjMat) = 0

test_fig = qgraph(adjMat,
                vsize = 8,
                layout = 'spring',
                edge.width = 1.5,
                pie = rsquare,
                fade = TRUE,
                labels = labels,
                groups = groups,
                legend = TRUE,
                # nodeNames = node_names,
                palette = "pastel",
                GLratio = 2.5,
                edge.labels = TRUE,
                title = 'T1 -> T2')

centrality(test_fig)
centralityPlot(test_fig, include = 'all', orderBy = 'OutExpectedInfluence')

adjMat <- glmModel[['B']][[2]]
diag(adjMat) = 0

test_fig = qgraph(adjMat,
                vsize = 8,
                layout = 'spring',
                edge.width = 1.5,
                pie = rsquare,
                fade = TRUE,
                labels = labels,
                groups = groups,
                legend = TRUE,
                # nodeNames = node_names,
                palette = "pastel",
                GLratio = 2.5,
                edge.labels = TRUE,
                title = 'T2 -> T3')

centrality(test_fig)
centralityPlot(test_fig, include = 'all', orderBy = 'OutExpectedInfluence')
```